"""fixed

Revision ID: 41e192e99ca2
Revises: 7577f2fd32b4
Create Date: 2022-10-25 16:22:43.647600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e192e99ca2'
down_revision = '7577f2fd32b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
