"""fixed----

Revision ID: 80c729b959ad
Revises: 6b293ae02235
Create Date: 2022-10-26 11:20:55.634500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c729b959ad'
down_revision = '6b293ae02235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
